In [110]:
import numpy as np
import pandas as pd

In [111]:
df = pd.read_csv('iris.csv')

In [112]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [113]:
df["Id"].drop

<bound method Series.drop of 0        1
1        2
2        3
3        4
4        5
      ... 
145    146
146    147
147    148
148    149
149    150
Name: Id, Length: 150, dtype: int64>

In [114]:
X = df.iloc[:,1:5].values

In [115]:
y = df.iloc[:,5:].values

In [116]:
#class 0 --> [1,0,0]
#class 1 --> [0,1,0]
#class 2 --> [0,0,1]

In [117]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [118]:
### integer mapping using LabelEncoder
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(y)
print(integer_encoded)
# integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


C:\Users\13kau\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [119]:
from keras.utils import to_categorical

In [120]:
y = to_categorical(integer_encoded)

In [121]:
y.shape

(150, 3)

In [122]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [123]:
from sklearn.model_selection import train_test_split

In [124]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [125]:
from sklearn.preprocessing import MinMaxScaler #scaling the value to 0, 1

In [126]:
mini = MinMaxScaler()

In [127]:
mini.fit(X_train)

MinMaxScaler()

In [128]:
X_scaled_train = mini.transform(X_train)

In [129]:
X_scaled_test = mini.transform(X_test)

In [130]:
# Build network of keras

In [131]:
from keras.models import Sequential
from keras.layers import Dense

In [132]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu')) #to create 8 neurons, #input layer
model.add(Dense(8, input_dim=4, activation='relu')) #to create 8 neurons
model.add(Dense(3, activation='softmax')) #to create 8 neurons, #outut layer
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [133]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_17 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_18 (Dense)             (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [134]:
model.fit(X_scaled_train, y_train,epochs=150, verbose=2) #verbose-- > output

Epoch 1/150
4/4 - 0s - loss: 1.1436 - accuracy: 0.3400
Epoch 2/150
4/4 - 0s - loss: 1.1343 - accuracy: 0.3400
Epoch 3/150
4/4 - 0s - loss: 1.1252 - accuracy: 0.3500
Epoch 4/150
4/4 - 0s - loss: 1.1173 - accuracy: 0.3500
Epoch 5/150
4/4 - 0s - loss: 1.1109 - accuracy: 0.3500
Epoch 6/150
4/4 - 0s - loss: 1.1037 - accuracy: 0.3500
Epoch 7/150
4/4 - 0s - loss: 1.0966 - accuracy: 0.3500
Epoch 8/150
4/4 - 0s - loss: 1.0902 - accuracy: 0.3500
Epoch 9/150
4/4 - 0s - loss: 1.0842 - accuracy: 0.3600
Epoch 10/150
4/4 - 0s - loss: 1.0777 - accuracy: 0.3400
Epoch 11/150
4/4 - 0s - loss: 1.0716 - accuracy: 0.3300
Epoch 12/150
4/4 - 0s - loss: 1.0656 - accuracy: 0.3400
Epoch 13/150
4/4 - 0s - loss: 1.0602 - accuracy: 0.3700
Epoch 14/150
4/4 - 0s - loss: 1.0536 - accuracy: 0.3400
Epoch 15/150
4/4 - 0s - loss: 1.0470 - accuracy: 0.3500
Epoch 16/150
4/4 - 0s - loss: 1.0415 - accuracy: 0.3400
Epoch 17/150
4/4 - 0s - loss: 1.0351 - accuracy: 0.3400
Epoch 18/150
4/4 - 0s - loss: 1.0301 - accuracy: 0.3400
E

Epoch 147/150
4/4 - 0s - loss: 0.4041 - accuracy: 0.9400
Epoch 148/150
4/4 - 0s - loss: 0.4025 - accuracy: 0.9200
Epoch 149/150
4/4 - 0s - loss: 0.3999 - accuracy: 0.9200
Epoch 150/150
4/4 - 0s - loss: 0.3976 - accuracy: 0.9200


In [135]:
model.predict_classes(X_scaled_test)

C:\Users\13kau\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [136]:
predictions =model.predict_classes(X_scaled_test)

C:\Users\13kau\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [138]:
y_test.argmax(axis=1) #reports back the original classes

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [140]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [143]:
print(accuracy_score(y_test.argmax(axis=1), predictions))

0.94


In [144]:
print(confusion_matrix(y_test.argmax(axis=1), predictions))

[[19  0  0]
 [ 0 12  3]
 [ 0  0 16]]


In [145]:
print(classification_report(y_test.argmax(axis=1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.80      0.89        15
           2       0.84      1.00      0.91        16

    accuracy                           0.94        50
   macro avg       0.95      0.93      0.93        50
weighted avg       0.95      0.94      0.94        50



In [146]:
model.save('myFirstproj.h5')

In [147]:
from keras.models import load_model

In [148]:
new_model = load_model('myFirstproj.h5')

In [149]:
new_model.predict_classes(X_scaled_test)

C:\Users\13kau\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1, 0, 2, 2, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)